### ISSUE TITLE
Cant run storybook or build commands

### ISSUE THREAD

**Issue by davidpaulmcintyre** [cwlsn/rinse-react#16]
i followed the instructions for creating a new project exactly, but i cant start storybook or build.

npm run storybook

> rinse-react@2.0.0 storybook dev/cool-name
> start-storybook -p 9001

dev/cool-name/node_modules/postcss/node_modules/source-map/lib/quick-sort.js:1
(function (exports, require, module, __filename, __dirname) { �
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/david/Documents/dev/cool-name/node_modules/postcss/node_modules/source-map/lib/source-map-consumer.js:12:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rinse-react@2.0.0 storybook: `start-storybook -p 9001`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rinse-react@2.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david/.npm/_logs/2019-01-15T14_25_10_570Z-debug.log

**Comment by cwlsn** [comment]
Hey! Thanks for the Issue report!

Did you clone into the folder `dev/cool-name`? The forward slash may cause issues. 

Otherwise, try going into the folder you've cloned into, `rm -rf node_modules` and then try to `npm install` and `npm run storybook` again. I just gave it a test and it seems to be working fine.

**Comment by davidpaulmcintyre** [comment]
I am using mac osx. If i use “cool” insteas of cool-name as the app and directory name it works as expected. So pls modify your doc

**Comment by cwlsn** [comment]
The commands in the readme work copy/pasted on Mac OSX for me, I think the issue was around the `dev/` part.

**Comment by davidpaulmcintyre** [comment]
To clarify i didnt include “dev” or “dev/“ in any of the commands. I executes the commands in both cases from dev

**Comment by cwlsn** [comment]
Ah, it should work if you `cd cool-name`. Those commands should always be run from the project's root folder.

**Comment by davidpaulmcintyre** [comment]
That is what i did
