### ISSUE TITLE
Loosing all styles

### ISSUE THREAD

**Issue by martinmcneela** [cwlsn/rinse-react#18]
I have installed 'rinse-react' and tried to use the default button component. When I import the Button into the javascript using `import { Button } from 'rinse-react';` I loose all other styling on my app.

The app I am using it with is built using styled-components and as soon as I remove the import the styling in my app returns.

**Comment by cwlsn** [comment]
That's strange! Is it possible there's a conflict of versions of `styled-components`? There is no CSS reset in the code here.
