### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by jpkontreras** [cwlsn/rinse-react#19]
Hello. 
im worried about the initial size of the bundle.
Only with the default button component the bundle has a size of 153kb 

![image](https://user-images.githubusercontent.com/7862089/55021214-2216e700-4fd7-11e9-848e-99ccfa282ff7.png)

The bundle has the  full react library , Object assign and scheduler.production.min.js.
Is there a reason for this?
Thanks.

**Comment by cwlsn** [comment]
Hey! There have been no optimizations made, as this is intended to be more educational in nature. I do plan on building out a few more components and leveling up the webpack config in the future.

**Comment by qramilq** [comment]
Hello!
@cwlsn  Any updates here?
