### ISSUE TITLE
Docz doesn't work with newly cloned project

### ISSUE THREAD

**Issue by mrsauravsahu** [cwlsn/rinse-react#34]
After cloning react-rinse for a new project, docz doesn't seem to work.

System Specs:
```bash
$ node -v
10.16.3
$ yarn -v 
1.19.0
```

![Screenshot from 2019-10-05 10-44-25](https://user-images.githubusercontent.com/9134050/66250235-93410f00-e75d-11e9-9684-30436e3f2671.png)

Resolution: Tried upgrading webpack and everything seems to be working.
I can open up a PR for the same.

**Comment by cwlsn** [comment]
Fixed in #35
